# Excluir archivos específicos
[[rules]]
description = "Excluir archivo secrets.yml"
files = ['^deploy/secrets\\.yml$']

# Permitir expresiones regulares específicas
[[rules]]
description = "Allowlist para secretos específicos"
    [rules.allowlist]
    paths = ["deploy/secrets.yml"]
    regexes = [
      '''^ZGphbmdvLWluc2VjdXJlLXdjMmkyKjZeMTckOSF1Kyh1NjZAcV9yZykrK24xeC1eKDAtJDN5ejJmKG49Xy1vKjc9$'''
    ]